# Generated by Django 4.1.3 on 2022-12-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article", options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["-comment_date"]},
        ),
    ]
